language: ruby
rvm:
  - "2.0.0"
  - "2.1.4"
  - "2.2.0"
  - "ruby-head"
  - "jruby-head"
  - "rbx-2.2.3"
matrix:
  allow_failures:
    - rvm: "ruby-head"
    - rvm: "jruby-head"
    - rvm: "rbx-2.2.3"
script: rake
